import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import GAListener from "@/lib/ga/GAListener";
import { initGA } from "../lib/ga";
import { VisitorTracker } from "@/components/VisitorTracker";

initGA(); // Initialize GA once

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL("https://hamdardcommittee.org"),
  title: "Hamdard Committee",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <VisitorTracker />
        <GAListener />

        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
